export const SESSION_DEFINITION_CREATE_BEGIN = 'SESSION_DEFINITION_CREATE_BEGIN';
export const SESSION_DEFINITION_CREATE_SUCCESS = 'SESSION_DEFINITION_CREATE_SUCCESS';
export const SESSION_DEFINITION_CREATE_FAILURE = 'SESSION_DEFINITION_CREATE_FAILURE';
export const SESSION_DEFINITION_CREATE_DISMISS_ERROR = 'SESSION_DEFINITION_CREATE_DISMISS_ERROR';
