import React, { Suspense } from 'react';
import CachedRoundedIcon from '@material-ui/icons/CachedRounded';
import { makeStyles } from '@material-ui/core';

const useStyles = makeStyles((theme) => ({
  colored: {
    color: ({ color }: { color: string }) => color || theme.palette.divider,
  },
}));

const LoadingIcon = () => <CachedRoundedIcon />;

type Props = {
  color: string;
  className: string;
  Component: any;
};

const Renderer = ({ color, className, Component }: Props) => {
  const classes = useStyles({ color });
  return <Component className={`${classes.colored} ${className}`}></Component>;
};

/**
 * Creates a react-loadable  Icon component.
 */
function loadableIcon(importFn: () => any) {
  const Inner = React.lazy(async () => {
    const component = await importFn();
    return {
      default(props) {
        return <Renderer {...props} Component={component.default} />;
      },
    };
  });
  const SuspendedIcon = (props) => (
    <Suspense fallback={<LoadingIcon />}>
      <Inner {...props} />
    </Suspense>
  );
  return SuspendedIcon;
}

/* scrapped from material-ui gh repo with
`console.log([...document.getElementsByClassName('js-navigation-open')].map( x => x.title.split('.')[0]).filter(x=>x?.includes('Outline')))`
then templated with 
regex: '(\w+)',
export const $1 = () => import('@material-ui/icons/$1')
export const $1 = loadableIcon(() => import('@material-ui/icons/$1'))
*/
// prettier-ignore
export const Default = loadableIcon(() => import('@material-ui/icons/BlockOutlined'));
export const AcUnitOutlined = loadableIcon(() => import('@material-ui/icons/AcUnitOutlined'));
export const AccessTimeOutlined = loadableIcon(() => import('@material-ui/icons/AccessTimeOutlined'));
export const AccessibilityNewOutlined = loadableIcon(() => import('@material-ui/icons/AccessibilityNewOutlined'));
export const AccessibleOutlined = loadableIcon(() => import('@material-ui/icons/AccessibleOutlined'));
export const AccountBalanceOutlined = loadableIcon(() => import('@material-ui/icons/AccountBalanceOutlined'));
export const AccountBalanceWalletOutlined = loadableIcon(() => import('@material-ui/icons/AccountBalanceWalletOutlined'));
export const AccountCircleOutlined = loadableIcon(() => import('@material-ui/icons/AccountCircleOutlined'));
export const AccountTreeOutlined = loadableIcon(() => import('@material-ui/icons/AccountTreeOutlined'));
export const AdbOutlined = loadableIcon(() => import('@material-ui/icons/AdbOutlined'));
export const AddIcCallOutlined = loadableIcon(() => import('@material-ui/icons/AddIcCallOutlined'));
export const AirlineSeatFlatAngledOutlined = loadableIcon(() => import('@material-ui/icons/AirlineSeatFlatAngledOutlined'));
export const AirlineSeatFlatOutlined = loadableIcon(() => import('@material-ui/icons/AirlineSeatFlatOutlined'));
export const AirlineSeatIndividualSuiteOutlined = loadableIcon(() => import('@material-ui/icons/AirlineSeatIndividualSuiteOutlined'));
export const AirlineSeatReclineNormalOutlined = loadableIcon(() => import('@material-ui/icons/AirlineSeatReclineNormalOutlined'));
export const AirplanemodeActiveOutlined = loadableIcon(() => import('@material-ui/icons/AirplanemodeActiveOutlined'));
export const AirplanemodeInactiveOutlined = loadableIcon(() => import('@material-ui/icons/AirplanemodeInactiveOutlined'));
export const AirportShuttleOutlined = loadableIcon(() => import('@material-ui/icons/AirportShuttleOutlined'));
export const AlarmOnOutlined = loadableIcon(() => import('@material-ui/icons/AlarmOnOutlined'));
export const AllInboxOutlined = loadableIcon(() => import('@material-ui/icons/AllInboxOutlined'));
export const AndroidOutlined = loadableIcon(() => import('@material-ui/icons/AndroidOutlined'));
export const AnnouncementOutlined = loadableIcon(() => import('@material-ui/icons/AnnouncementOutlined'));
export const ApartmentOutlined = loadableIcon(() => import('@material-ui/icons/ApartmentOutlined'));
export const AssignmentIndOutlined = loadableIcon(() => import('@material-ui/icons/AssignmentIndOutlined'));
export const AssignmentOutlined = loadableIcon(() => import('@material-ui/icons/AssignmentOutlined'));
export const AssistantPhotoOutlined = loadableIcon(() => import('@material-ui/icons/AssistantPhotoOutlined'));
export const AttachFileOutlined = loadableIcon(() => import('@material-ui/icons/AttachFileOutlined'));
export const AttachMoneyOutlined = loadableIcon(() => import('@material-ui/icons/AttachMoneyOutlined'));
export const AttachmentOutlined = loadableIcon(() => import('@material-ui/icons/AttachmentOutlined'));
export const AudiotrackOutlined = loadableIcon(() => import('@material-ui/icons/AudiotrackOutlined'));
export const BackupOutlined = loadableIcon(() => import('@material-ui/icons/BackupOutlined'));
export const BallotOutlined = loadableIcon(() => import('@material-ui/icons/BallotOutlined'));
export const BathtubOutlined = loadableIcon(() => import('@material-ui/icons/BathtubOutlined'));
export const BatteryChargingFullOutlined = loadableIcon(() => import('@material-ui/icons/BatteryChargingFullOutlined'));
export const BatteryFullOutlined = loadableIcon(() => import('@material-ui/icons/BatteryFullOutlined'));
export const BeachAccessOutlined = loadableIcon(() => import('@material-ui/icons/BeachAccessOutlined'));
export const BeenhereOutlined = loadableIcon(() => import('@material-ui/icons/BeenhereOutlined'));
export const BlockOutlined = loadableIcon(() => import('@material-ui/icons/BlockOutlined'));
export const BookOutlined = loadableIcon(() => import('@material-ui/icons/BookOutlined'));
export const BookmarkBorderOutlined = loadableIcon(() => import('@material-ui/icons/BookmarkBorderOutlined'));
export const Brightness5Outlined = loadableIcon(() => import('@material-ui/icons/Brightness5Outlined'));
export const BrokenImageOutlined = loadableIcon(() => import('@material-ui/icons/BrokenImageOutlined'));
export const BugReportOutlined = loadableIcon(() => import('@material-ui/icons/BugReportOutlined'));
export const BuildOutlined = loadableIcon(() => import('@material-ui/icons/BuildOutlined'));
export const BusinessCenterOutlined = loadableIcon(() => import('@material-ui/icons/BusinessCenterOutlined'));
export const BusinessOutlined = loadableIcon(() => import('@material-ui/icons/BusinessOutlined'));
export const CakeOutlined = loadableIcon(() => import('@material-ui/icons/CakeOutlined'));
export const CalendarTodayOutlined = loadableIcon(() => import('@material-ui/icons/CalendarTodayOutlined'));
export const CameraAltOutlined = loadableIcon(() => import('@material-ui/icons/CameraAltOutlined'));
export const CameraOutlined = loadableIcon(() => import('@material-ui/icons/CameraOutlined'));
export const CameraRollOutlined = loadableIcon(() => import('@material-ui/icons/CameraRollOutlined'));
export const CancelOutlined = loadableIcon(() => import('@material-ui/icons/CancelOutlined'));
export const CasinoOutlined = loadableIcon(() => import('@material-ui/icons/CasinoOutlined'));
export const CategoryOutlined = loadableIcon(() => import('@material-ui/icons/CategoryOutlined'));
export const CheckCircleOutlined = loadableIcon(() => import('@material-ui/icons/CheckCircleOutlined'));
export const ChildCareOutlined = loadableIcon(() => import('@material-ui/icons/ChildCareOutlined'));
export const ChildFriendlyOutlined = loadableIcon(() => import('@material-ui/icons/ChildFriendlyOutlined'));
export const ChromeReaderModeOutlined = loadableIcon(() => import('@material-ui/icons/ChromeReaderModeOutlined'));
export const ClassOutlined = loadableIcon(() => import('@material-ui/icons/ClassOutlined'));

export const CloudCircleOutlined = loadableIcon(() => import('@material-ui/icons/CloudCircleOutlined'));
export const CloudOutlined = loadableIcon(() => import('@material-ui/icons/CloudOutlined'));

export const ColorizeOutlined = loadableIcon(() => import('@material-ui/icons/ColorizeOutlined'));
export const CommuteOutlined = loadableIcon(() => import('@material-ui/icons/CommuteOutlined'));

export const CompassCalibrationOutlined = loadableIcon(() => import('@material-ui/icons/CompassCalibrationOutlined'));
export const ConfirmationNumberOutlined = loadableIcon(() => import('@material-ui/icons/ConfirmationNumberOutlined'));
export const ContactlessOutlined = loadableIcon(() => import('@material-ui/icons/ContactlessOutlined'));
export const ContactMailOutlined = loadableIcon(() => import('@material-ui/icons/ContactMailOutlined'));


export const CopyrightOutlined = loadableIcon(() => import('@material-ui/icons/CopyrightOutlined'));
export const CreateOutlined = loadableIcon(() => import('@material-ui/icons/CreateOutlined'));
export const CreditCardOutlined = loadableIcon(() => import('@material-ui/icons/CreditCardOutlined'));

export const DashboardOutlined = loadableIcon(() => import('@material-ui/icons/DashboardOutlined'));
export const DateRangeOutlined = loadableIcon(() => import('@material-ui/icons/DateRangeOutlined'));
export const DeckOutlined = loadableIcon(() => import('@material-ui/icons/DeckOutlined'));
export const DeleteOutlineOutlined = loadableIcon(() => import('@material-ui/icons/DeleteOutlineOutlined'));
export const DepartureBoardOutlined = loadableIcon(() => import('@material-ui/icons/DepartureBoardOutlined'));
export const DescriptionOutlined = loadableIcon(() => import('@material-ui/icons/DescriptionOutlined'));
export const DesktopMacOutlined = loadableIcon(() => import('@material-ui/icons/DesktopMacOutlined'));
export const DesktopWindowsOutlined = loadableIcon(() => import('@material-ui/icons/DesktopWindowsOutlined'));
export const DeveloperBoardOutlined = loadableIcon(() => import('@material-ui/icons/DeveloperBoardOutlined'));
export const DevicesOtherOutlined = loadableIcon(() => import('@material-ui/icons/DevicesOtherOutlined'));
export const DevicesOutlined = loadableIcon(() => import('@material-ui/icons/DevicesOutlined'));
export const DirectionsBikeOutlined = loadableIcon(() => import('@material-ui/icons/DirectionsBikeOutlined'));
export const DirectionsBoatOutlined = loadableIcon(() => import('@material-ui/icons/DirectionsBoatOutlined'));
export const DirectionsBusOutlined = loadableIcon(() => import('@material-ui/icons/DirectionsBusOutlined'));
export const DirectionsCarOutlined = loadableIcon(() => import('@material-ui/icons/DirectionsCarOutlined'));
export const DirectionsRailwayOutlined = loadableIcon(() => import('@material-ui/icons/DirectionsRailwayOutlined'));
export const DirectionsRunOutlined = loadableIcon(() => import('@material-ui/icons/DirectionsRunOutlined'));
export const DirectionsSubwayOutlined = loadableIcon(() => import('@material-ui/icons/DirectionsSubwayOutlined'));
export const DirectionsWalkOutlined = loadableIcon(() => import('@material-ui/icons/DirectionsWalkOutlined'));
export const DnsOutlined = loadableIcon(() => import('@material-ui/icons/DnsOutlined'));
export const DoneOutlineOutlined = loadableIcon(() => import('@material-ui/icons/DoneOutlineOutlined'));
export const DonutLargeOutlined = loadableIcon(() => import('@material-ui/icons/DonutLargeOutlined'));
export const DonutSmallOutlined = loadableIcon(() => import('@material-ui/icons/DonutSmallOutlined'));
export const DoubleArrowOutlined = loadableIcon(() => import('@material-ui/icons/DoubleArrowOutlined'));
export const DraftsOutlined = loadableIcon(() => import('@material-ui/icons/DraftsOutlined'));
export const DuoOutlined = loadableIcon(() => import('@material-ui/icons/DuoOutlined'));
export const DvrOutlined = loadableIcon(() => import('@material-ui/icons/DvrOutlined'));
export const EcoOutlined = loadableIcon(() => import('@material-ui/icons/EcoOutlined'));
export const EmojiEmotionsOutlined = loadableIcon(() => import('@material-ui/icons/EmojiEmotionsOutlined'));
export const EmojiEventsOutlined = loadableIcon(() => import('@material-ui/icons/EmojiEventsOutlined'));
export const EmojiFlagsOutlined = loadableIcon(() => import('@material-ui/icons/EmojiFlagsOutlined'));
export const EmojiFoodBeverageOutlined = loadableIcon(() => import('@material-ui/icons/EmojiFoodBeverageOutlined'));
export const EmojiNatureOutlined = loadableIcon(() => import('@material-ui/icons/EmojiNatureOutlined'));
export const EmojiObjectsOutlined = loadableIcon(() => import('@material-ui/icons/EmojiObjectsOutlined'));
export const EmojiSymbolsOutlined = loadableIcon(() => import('@material-ui/icons/EmojiSymbolsOutlined'));
export const EmojiTransportationOutlined = loadableIcon(() => import('@material-ui/icons/EmojiTransportationOutlined'));
export const ErrorOutlineOutlined = loadableIcon(() => import('@material-ui/icons/ErrorOutlineOutlined'));
export const EuroSymbolOutlined = loadableIcon(() => import('@material-ui/icons/EuroSymbolOutlined'));
export const EventAvailableOutlined = loadableIcon(() => import('@material-ui/icons/EventAvailableOutlined'));
export const EventOutlined = loadableIcon(() => import('@material-ui/icons/EventOutlined'));
export const EvStationOutlined = loadableIcon(() => import('@material-ui/icons/EvStationOutlined'));
export const ExploreOutlined = loadableIcon(() => import('@material-ui/icons/ExploreOutlined'));
export const ExtensionOutlined = loadableIcon(() => import('@material-ui/icons/ExtensionOutlined'));
export const FaceOutlined = loadableIcon(() => import('@material-ui/icons/FaceOutlined'));
export const FastfoodOutlined = loadableIcon(() => import('@material-ui/icons/FastfoodOutlined'));
export const FavoriteBorderOutlined = loadableIcon(() => import('@material-ui/icons/FavoriteBorderOutlined'));
export const FavoriteOutlined = loadableIcon(() => import('@material-ui/icons/FavoriteOutlined'));
export const FeedbackOutlined = loadableIcon(() => import('@material-ui/icons/FeedbackOutlined'));
export const FilterDramaOutlined = loadableIcon(() => import('@material-ui/icons/FilterDramaOutlined'));
export const FilterVintageOutlined = loadableIcon(() => import('@material-ui/icons/FilterVintageOutlined'));
export const FindInPageOutlined = loadableIcon(() => import('@material-ui/icons/FindInPageOutlined'));
export const FingerprintOutlined = loadableIcon(() => import('@material-ui/icons/FingerprintOutlined'));
export const FireplaceOutlined = loadableIcon(() => import('@material-ui/icons/FireplaceOutlined'));
export const FitnessCenterOutlined = loadableIcon(() => import('@material-ui/icons/FitnessCenterOutlined'));
export const FlagOutlined = loadableIcon(() => import('@material-ui/icons/FlagOutlined'));
export const FlareOutlined = loadableIcon(() => import('@material-ui/icons/FlareOutlined'));
export const FlightLandOutlined = loadableIcon(() => import('@material-ui/icons/FlightLandOutlined'));
export const FlightTakeoffOutlined = loadableIcon(() => import('@material-ui/icons/FlightTakeoffOutlined'));
export const FolderOutlined = loadableIcon(() => import('@material-ui/icons/FolderOutlined'));
export const FolderSharedOutlined = loadableIcon(() => import('@material-ui/icons/FolderSharedOutlined'));
export const FolderSpecialOutlined = loadableIcon(() => import('@material-ui/icons/FolderSpecialOutlined'));
export const FormatPaintOutlined = loadableIcon(() => import('@material-ui/icons/FormatPaintOutlined'));
export const FormatQuoteOutlined = loadableIcon(() => import('@material-ui/icons/FormatQuoteOutlined'));
export const ForumOutlined = loadableIcon(() => import('@material-ui/icons/ForumOutlined'));
export const FreeBreakfastOutlined = loadableIcon(() => import('@material-ui/icons/FreeBreakfastOutlined'));
export const FunctionsOutlined = loadableIcon(() => import('@material-ui/icons/FunctionsOutlined'));
export const GamesOutlined = loadableIcon(() => import('@material-ui/icons/GamesOutlined'));
export const GavelOutlined = loadableIcon(() => import('@material-ui/icons/GavelOutlined'));
export const GolfCourseOutlined = loadableIcon(() => import('@material-ui/icons/GolfCourseOutlined'));
export const GpsFixedOutlined = loadableIcon(() => import('@material-ui/icons/GpsFixedOutlined'));
export const GradeOutlined = loadableIcon(() => import('@material-ui/icons/GradeOutlined'));
export const GradientOutlined = loadableIcon(() => import('@material-ui/icons/GradientOutlined'));
export const GroupWorkOutlined = loadableIcon(() => import('@material-ui/icons/GroupWorkOutlined'));
export const GTranslateOutlined = loadableIcon(() => import('@material-ui/icons/GTranslateOutlined'));
export const HeadsetOutlined = loadableIcon(() => import('@material-ui/icons/HeadsetOutlined'));
export const HealingOutlined = loadableIcon(() => import('@material-ui/icons/HealingOutlined'));
export const HearingOutlined = loadableIcon(() => import('@material-ui/icons/HearingOutlined'));
export const HelpOutlined = loadableIcon(() => import('@material-ui/icons/HelpOutlined'));
export const HelpOutlineOutlined = loadableIcon(() => import('@material-ui/icons/HelpOutlineOutlined'));
export const HomeOutlined = loadableIcon(() => import('@material-ui/icons/HomeOutlined'));
export const HomeWorkOutlined = loadableIcon(() => import('@material-ui/icons/HomeWorkOutlined'));
export const HotelOutlined = loadableIcon(() => import('@material-ui/icons/HotelOutlined'));
export const HotTubOutlined = loadableIcon(() => import('@material-ui/icons/HotTubOutlined'));
export const HouseOutlined = loadableIcon(() => import('@material-ui/icons/HouseOutlined'));
export const HowToVoteOutlined = loadableIcon(() => import('@material-ui/icons/HowToVoteOutlined'));
export const HttpsOutlined = loadableIcon(() => import('@material-ui/icons/HttpsOutlined'));
export const ImageOutlined = loadableIcon(() => import('@material-ui/icons/ImageOutlined'));
export const InboxOutlined = loadableIcon(() => import('@material-ui/icons/InboxOutlined'));
export const InfoOutlined = loadableIcon(() => import('@material-ui/icons/InfoOutlined'));
export const InsertChartOutlinedTwoTone = loadableIcon(() => import('@material-ui/icons/InsertChartOutlinedTwoTone'));
export const InsertDriveFileOutlined = loadableIcon(() => import('@material-ui/icons/InsertDriveFileOutlined'));
export const InsertEmoticonOutlined = loadableIcon(() => import('@material-ui/icons/InsertEmoticonOutlined'));
export const InvertColorsOutlined = loadableIcon(() => import('@material-ui/icons/InvertColorsOutlined'));
export const IsoOutlined = loadableIcon(() => import('@material-ui/icons/IsoOutlined'));
export const KeyboardOutlined = loadableIcon(() => import('@material-ui/icons/KeyboardOutlined'));
export const KingBedOutlined = loadableIcon(() => import('@material-ui/icons/KingBedOutlined'));
export const KitchenOutlined = loadableIcon(() => import('@material-ui/icons/KitchenOutlined'));
export const LandscapeOutlined = loadableIcon(() => import('@material-ui/icons/LandscapeOutlined'));
export const LanguageOutlined = loadableIcon(() => import('@material-ui/icons/LanguageOutlined'));
export const LaptopChromebookOutlined = loadableIcon(() => import('@material-ui/icons/LaptopChromebookOutlined'));
export const LinkedCameraOutlined = loadableIcon(() => import('@material-ui/icons/LinkedCameraOutlined'));
export const LocalActivityOutlined = loadableIcon(() => import('@material-ui/icons/LocalActivityOutlined'));
export const LocalAtmOutlined = loadableIcon(() => import('@material-ui/icons/LocalAtmOutlined'));
export const LocalBarOutlined = loadableIcon(() => import('@material-ui/icons/LocalBarOutlined'));
export const LocalCafeOutlined = loadableIcon(() => import('@material-ui/icons/LocalCafeOutlined'));
export const LocalCarWashOutlined = loadableIcon(() => import('@material-ui/icons/LocalCarWashOutlined'));
export const LocalDiningOutlined = loadableIcon(() => import('@material-ui/icons/LocalDiningOutlined'));
export const LocalDrinkOutlined = loadableIcon(() => import('@material-ui/icons/LocalDrinkOutlined'));
export const LocalFloristOutlined = loadableIcon(() => import('@material-ui/icons/LocalFloristOutlined'));
export const LocalGasStationOutlined = loadableIcon(() => import('@material-ui/icons/LocalGasStationOutlined'));
export const LocalLaundryServiceOutlined = loadableIcon(() => import('@material-ui/icons/LocalLaundryServiceOutlined'));
export const LocalLibraryOutlined = loadableIcon(() => import('@material-ui/icons/LocalLibraryOutlined'));
export const LocalMallOutlined = loadableIcon(() => import('@material-ui/icons/LocalMallOutlined'));
export const LocalMoviesOutlined = loadableIcon(() => import('@material-ui/icons/LocalMoviesOutlined'));
export const LocalOfferOutlined = loadableIcon(() => import('@material-ui/icons/LocalOfferOutlined'));
export const LocalParkingOutlined = loadableIcon(() => import('@material-ui/icons/LocalParkingOutlined'));
export const LocalPharmacyOutlined = loadableIcon(() => import('@material-ui/icons/LocalPharmacyOutlined'));
export const LocalPizzaOutlined = loadableIcon(() => import('@material-ui/icons/LocalPizzaOutlined'));
export const LocalPlayOutlined = loadableIcon(() => import('@material-ui/icons/LocalPlayOutlined'));
export const LocalShippingOutlined = loadableIcon(() => import('@material-ui/icons/LocalShippingOutlined'));
export const LocalTaxiOutlined = loadableIcon(() => import('@material-ui/icons/LocalTaxiOutlined'));
export const LocationCityOutlined = loadableIcon(() => import('@material-ui/icons/LocationCityOutlined'));
export const LocationOffOutlined = loadableIcon(() => import('@material-ui/icons/LocationOffOutlined'));
export const LocationOnOutlined = loadableIcon(() => import('@material-ui/icons/LocationOnOutlined'));
export const LockOpenOutlined = loadableIcon(() => import('@material-ui/icons/LockOpenOutlined'));
export const LockOutlined = loadableIcon(() => import('@material-ui/icons/LockOutlined'));
export const Looks3Outlined = loadableIcon(() => import('@material-ui/icons/Looks3Outlined'));
export const Looks4Outlined = loadableIcon(() => import('@material-ui/icons/Looks4Outlined'));
export const Looks5Outlined = loadableIcon(() => import('@material-ui/icons/Looks5Outlined'));
export const Looks6Outlined = loadableIcon(() => import('@material-ui/icons/Looks6Outlined'));
export const LooksOneOutlined = loadableIcon(() => import('@material-ui/icons/LooksOneOutlined'));
export const LooksOutlined = loadableIcon(() => import('@material-ui/icons/LooksOutlined'));
export const LooksTwoOutlined = loadableIcon(() => import('@material-ui/icons/LooksTwoOutlined'));
export const LoyaltyOutlined = loadableIcon(() => import('@material-ui/icons/LoyaltyOutlined'));
export const MailOutlined = loadableIcon(() => import('@material-ui/icons/MailOutlined'));
export const MapOutlined = loadableIcon(() => import('@material-ui/icons/MapOutlined'));
export const MarkunreadMailboxOutlined = loadableIcon(() => import('@material-ui/icons/MarkunreadMailboxOutlined'));
export const MeetingRoomOutlined = loadableIcon(() => import('@material-ui/icons/MeetingRoomOutlined'));
export const MemoryOutlined = loadableIcon(() => import('@material-ui/icons/MemoryOutlined'));
export const MenuBookOutlined = loadableIcon(() => import('@material-ui/icons/MenuBookOutlined'));
export const MessageOutlined = loadableIcon(() => import('@material-ui/icons/MessageOutlined'));
export const MicNoneOutlined = loadableIcon(() => import('@material-ui/icons/MicNoneOutlined'));
export const MmsOutlined = loadableIcon(() => import('@material-ui/icons/MmsOutlined'));
export const MonetizationOnOutlined = loadableIcon(() => import('@material-ui/icons/MonetizationOnOutlined'));
export const MoneyOutlined = loadableIcon(() => import('@material-ui/icons/MoneyOutlined'));
export const MonochromePhotosOutlined = loadableIcon(() => import('@material-ui/icons/MonochromePhotosOutlined'));
export const MoodBadOutlined = loadableIcon(() => import('@material-ui/icons/MoodBadOutlined'));
export const MoodOutlined = loadableIcon(() => import('@material-ui/icons/MoodOutlined'));
export const MotorcycleOutlined = loadableIcon(() => import('@material-ui/icons/MotorcycleOutlined'));
export const MouseOutlined = loadableIcon(() => import('@material-ui/icons/MouseOutlined'));
export const MovieCreationOutlined = loadableIcon(() => import('@material-ui/icons/MovieCreationOutlined'));
export const MuseumOutlined = loadableIcon(() => import('@material-ui/icons/MuseumOutlined'));
export const MusicVideoOutlined = loadableIcon(() => import('@material-ui/icons/MusicVideoOutlined'));
export const NatureOutlined = loadableIcon(() => import('@material-ui/icons/NatureOutlined'));
export const NavigationOutlined = loadableIcon(() => import('@material-ui/icons/NavigationOutlined'));
export const NetworkCellOutlined = loadableIcon(() => import('@material-ui/icons/NetworkCellOutlined'));
export const NetworkCheckOutlined = loadableIcon(() => import('@material-ui/icons/NetworkCheckOutlined'));
export const NetworkWifiOutlined = loadableIcon(() => import('@material-ui/icons/NetworkWifiOutlined'));
export const NewReleasesOutlined = loadableIcon(() => import('@material-ui/icons/NewReleasesOutlined'));
export const NfcOutlined = loadableIcon(() => import('@material-ui/icons/NfcOutlined'));
export const NightsStayOutlined = loadableIcon(() => import('@material-ui/icons/NightsStayOutlined'));
export const NotificationsActiveOutlined = loadableIcon(() => import('@material-ui/icons/NotificationsActiveOutlined'));
export const NotificationsNoneOutlined = loadableIcon(() => import('@material-ui/icons/NotificationsNoneOutlined'));
export const NotListedLocationOutlined = loadableIcon(() => import('@material-ui/icons/NotListedLocationOutlined'));
export const OfflineBoltOutlined = loadableIcon(() => import('@material-ui/icons/OfflineBoltOutlined'));
export const OndemandVideoOutlined = loadableIcon(() => import('@material-ui/icons/OndemandVideoOutlined'));
export const OpacityOutlined = loadableIcon(() => import('@material-ui/icons/OpacityOutlined'));
export const OpenWithOutlined = loadableIcon(() => import('@material-ui/icons/OpenWithOutlined'));
export const OutdoorGrillOutlined = loadableIcon(() => import('@material-ui/icons/OutdoorGrillOutlined'));
export const OutlinedFlag = loadableIcon(() => import('@material-ui/icons/OutlinedFlag'));
export const PagesOutlined = loadableIcon(() => import('@material-ui/icons/PagesOutlined'));
export const PageviewOutlined = loadableIcon(() => import('@material-ui/icons/PageviewOutlined'));
export const PaletteOutlined = loadableIcon(() => import('@material-ui/icons/PaletteOutlined'));
export const PanToolOutlined = loadableIcon(() => import('@material-ui/icons/PanToolOutlined'));
export const PeopleAltOutlined = loadableIcon(() => import('@material-ui/icons/PeopleAltOutlined'));
export const PermContactCalendarOutlined = loadableIcon(() => import('@material-ui/icons/PermContactCalendarOutlined'));
export const PermIdentityOutlined = loadableIcon(() => import('@material-ui/icons/PermIdentityOutlined'));
export const PersonOutlineOutlined = loadableIcon(() => import('@material-ui/icons/PersonOutlineOutlined'));
export const PersonPinCircleOutlined = loadableIcon(() => import('@material-ui/icons/PersonPinCircleOutlined'));
export const PersonPinOutlined = loadableIcon(() => import('@material-ui/icons/PersonPinOutlined'));
export const PetsOutlined = loadableIcon(() => import('@material-ui/icons/PetsOutlined'));
export const PhoneAndroidOutlined = loadableIcon(() => import('@material-ui/icons/PhoneAndroidOutlined'));
export const PhoneIphoneOutlined = loadableIcon(() => import('@material-ui/icons/PhoneIphoneOutlined'));
export const PhonelinkOffOutlined = loadableIcon(() => import('@material-ui/icons/PhonelinkOffOutlined'));
export const PhonelinkOutlined = loadableIcon(() => import('@material-ui/icons/PhonelinkOutlined'));
export const PhotoAlbumOutlined = loadableIcon(() => import('@material-ui/icons/PhotoAlbumOutlined'));
export const PhotoCameraOutlined = loadableIcon(() => import('@material-ui/icons/PhotoCameraOutlined'));
export const PhotoOutlined = loadableIcon(() => import('@material-ui/icons/PhotoOutlined'));
export const PieChartOutlined = loadableIcon(() => import('@material-ui/icons/PieChartOutlined'));
export const PolicyOutlined = loadableIcon(() => import('@material-ui/icons/PolicyOutlined'));
export const PollOutlined = loadableIcon(() => import('@material-ui/icons/PollOutlined'));
export const PolymerOutlined = loadableIcon(() => import('@material-ui/icons/PolymerOutlined'));
export const PoolOutlined = loadableIcon(() => import('@material-ui/icons/PoolOutlined'));
export const PortraitOutlined = loadableIcon(() => import('@material-ui/icons/PortraitOutlined'));
export const PowerOutlined = loadableIcon(() => import('@material-ui/icons/PowerOutlined'));
export const PowerSettingsNewOutlined = loadableIcon(() => import('@material-ui/icons/PowerSettingsNewOutlined'));
export const PregnantWomanOutlined = loadableIcon(() => import('@material-ui/icons/PregnantWomanOutlined'));
export const PresentToAllOutlined = loadableIcon(() => import('@material-ui/icons/PresentToAllOutlined'));
export const PrintOutlined = loadableIcon(() => import('@material-ui/icons/PrintOutlined'));
export const PriorityHighOutlined = loadableIcon(() => import('@material-ui/icons/PriorityHighOutlined'));
export const PublicOutlined = loadableIcon(() => import('@material-ui/icons/PublicOutlined'));
export const QueryBuilderOutlined = loadableIcon(() => import('@material-ui/icons/QueryBuilderOutlined'));
export const RadioOutlined = loadableIcon(() => import('@material-ui/icons/RadioOutlined'));
export const RateReviewOutlined = loadableIcon(() => import('@material-ui/icons/RateReviewOutlined'));
export const ReceiptOutlined = loadableIcon(() => import('@material-ui/icons/ReceiptOutlined'));
export const RecordVoiceOverOutlined = loadableIcon(() => import('@material-ui/icons/RecordVoiceOverOutlined'));
export const RemoveCircleOutlineOutlined = loadableIcon(() => import('@material-ui/icons/RemoveCircleOutlineOutlined'));
export const RemoveRedEyeOutlined = loadableIcon(() => import('@material-ui/icons/RemoveRedEyeOutlined'));
export const ReportOutlined = loadableIcon(() => import('@material-ui/icons/ReportOutlined'));
export const ReportProblemOutlined = loadableIcon(() => import('@material-ui/icons/ReportProblemOutlined'));
export const RestaurantOutlined = loadableIcon(() => import('@material-ui/icons/RestaurantOutlined'));
export const RingVolumeOutlined = loadableIcon(() => import('@material-ui/icons/RingVolumeOutlined'));
export const RoomOutlined = loadableIcon(() => import('@material-ui/icons/RoomOutlined'));
export const RoomServiceOutlined = loadableIcon(() => import('@material-ui/icons/RoomServiceOutlined'));
export const RouterOutlined = loadableIcon(() => import('@material-ui/icons/RouterOutlined'));
export const RowingOutlined = loadableIcon(() => import('@material-ui/icons/RowingOutlined'));
export const RssFeedOutlined = loadableIcon(() => import('@material-ui/icons/RssFeedOutlined'));
export const RvHookupOutlined = loadableIcon(() => import('@material-ui/icons/RvHookupOutlined'));
export const SatelliteOutlined = loadableIcon(() => import('@material-ui/icons/SatelliteOutlined'));
export const SaveOutlined = loadableIcon(() => import('@material-ui/icons/SaveOutlined'));
export const ScannerOutlined = loadableIcon(() => import('@material-ui/icons/ScannerOutlined'));
export const SchoolOutlined = loadableIcon(() => import('@material-ui/icons/SchoolOutlined'));
export const SdCardOutlined = loadableIcon(() => import('@material-ui/icons/SdCardOutlined'));
export const SecurityOutlined = loadableIcon(() => import('@material-ui/icons/SecurityOutlined'));
export const SentimentDissatisfiedOutlined = loadableIcon(() => import('@material-ui/icons/SentimentDissatisfiedOutlined'));
export const SentimentSatisfiedAltOutlined = loadableIcon(() => import('@material-ui/icons/SentimentSatisfiedAltOutlined'));
export const SentimentSatisfiedOutlined = loadableIcon(() => import('@material-ui/icons/SentimentSatisfiedOutlined'));
export const SentimentVeryDissatisfiedOutlined = loadableIcon(() => import('@material-ui/icons/SentimentVeryDissatisfiedOutlined'));
export const SentimentVerySatisfiedOutlined = loadableIcon(() => import('@material-ui/icons/SentimentVerySatisfiedOutlined'));
export const SettingsApplicationsOutlined = loadableIcon(() => import('@material-ui/icons/SettingsApplicationsOutlined'));
export const SettingsBrightnessOutlined = loadableIcon(() => import('@material-ui/icons/SettingsBrightnessOutlined'));
export const SettingsInputComponentOutlined = loadableIcon(() => import('@material-ui/icons/SettingsInputComponentOutlined'));
export const SettingsInputHdmiOutlined = loadableIcon(() => import('@material-ui/icons/SettingsInputHdmiOutlined'));
export const SettingsInputSvideoOutlined = loadableIcon(() => import('@material-ui/icons/SettingsInputSvideoOutlined'));
export const SettingsOutlined = loadableIcon(() => import('@material-ui/icons/SettingsOutlined'));
export const SettingsRemoteOutlined = loadableIcon(() => import('@material-ui/icons/SettingsRemoteOutlined'));
export const SettingsSystemDaydreamOutlined = loadableIcon(() => import('@material-ui/icons/SettingsSystemDaydreamOutlined'));
export const ShopOutlined = loadableIcon(() => import('@material-ui/icons/ShopOutlined'));
export const ShoppingBasketOutlined = loadableIcon(() => import('@material-ui/icons/ShoppingBasketOutlined'));
export const ShoppingCartOutlined = loadableIcon(() => import('@material-ui/icons/ShoppingCartOutlined'));
export const ShutterSpeedOutlined = loadableIcon(() => import('@material-ui/icons/ShutterSpeedOutlined'));
export const SimCardOutlined = loadableIcon(() => import('@material-ui/icons/SimCardOutlined'));
export const SingleBedOutlined = loadableIcon(() => import('@material-ui/icons/SingleBedOutlined'));
export const SmokingRoomsOutlined = loadableIcon(() => import('@material-ui/icons/SmokingRoomsOutlined'));
export const SmsOutlined = loadableIcon(() => import('@material-ui/icons/SmsOutlined'));
export const SpaOutlined = loadableIcon(() => import('@material-ui/icons/SpaOutlined'));
export const SpeakerOutlined = loadableIcon(() => import('@material-ui/icons/SpeakerOutlined'));
export const SpeedOutlined = loadableIcon(() => import('@material-ui/icons/SpeedOutlined'));
export const SportsBaseballOutlined = loadableIcon(() => import('@material-ui/icons/SportsBaseballOutlined'));
export const SportsBasketballOutlined = loadableIcon(() => import('@material-ui/icons/SportsBasketballOutlined'));
export const SportsCricketOutlined = loadableIcon(() => import('@material-ui/icons/SportsCricketOutlined'));
export const SportsEsportsOutlined = loadableIcon(() => import('@material-ui/icons/SportsEsportsOutlined'));
export const SportsFootballOutlined = loadableIcon(() => import('@material-ui/icons/SportsFootballOutlined'));
export const SportsGolfOutlined = loadableIcon(() => import('@material-ui/icons/SportsGolfOutlined'));
export const SportsHandballOutlined = loadableIcon(() => import('@material-ui/icons/SportsHandballOutlined'));
export const SportsHockeyOutlined = loadableIcon(() => import('@material-ui/icons/SportsHockeyOutlined'));
export const SportsKabaddiOutlined = loadableIcon(() => import('@material-ui/icons/SportsKabaddiOutlined'));
export const SportsMmaOutlined = loadableIcon(() => import('@material-ui/icons/SportsMmaOutlined'));
export const SportsMotorsportsOutlined = loadableIcon(() => import('@material-ui/icons/SportsMotorsportsOutlined'));
export const SportsOutlined = loadableIcon(() => import('@material-ui/icons/SportsOutlined'));
export const SportsRugbyOutlined = loadableIcon(() => import('@material-ui/icons/SportsRugbyOutlined'));
export const SportsSoccerOutlined = loadableIcon(() => import('@material-ui/icons/SportsSoccerOutlined'));
export const SportsTennisOutlined = loadableIcon(() => import('@material-ui/icons/SportsTennisOutlined'));
export const SportsVolleyballOutlined = loadableIcon(() => import('@material-ui/icons/SportsVolleyballOutlined'));
export const SquareFootOutlined = loadableIcon(() => import('@material-ui/icons/SquareFootOutlined'));
export const StarOutlined = loadableIcon(() => import('@material-ui/icons/StarOutlined'));
export const StarOutlineOutlined = loadableIcon(() => import('@material-ui/icons/StarOutlineOutlined'));
export const StarsOutlined = loadableIcon(() => import('@material-ui/icons/StarsOutlined'));
export const StorageOutlined = loadableIcon(() => import('@material-ui/icons/StorageOutlined'));
export const StorefrontOutlined = loadableIcon(() => import('@material-ui/icons/StorefrontOutlined'));
export const StoreMallDirectoryOutlined = loadableIcon(() => import('@material-ui/icons/StoreMallDirectoryOutlined'));
export const StraightenOutlined = loadableIcon(() => import('@material-ui/icons/StraightenOutlined'));
export const StyleOutlined = loadableIcon(() => import('@material-ui/icons/StyleOutlined'));
export const SubtitlesOutlined = loadableIcon(() => import('@material-ui/icons/SubtitlesOutlined'));
export const SubwayOutlined = loadableIcon(() => import('@material-ui/icons/SubwayOutlined'));
export const SupervisedUserCircleOutlined = loadableIcon(() => import('@material-ui/icons/SupervisedUserCircleOutlined'));
export const SupervisorAccountOutlined = loadableIcon(() => import('@material-ui/icons/SupervisorAccountOutlined'));
export const SurroundSoundOutlined = loadableIcon(() => import('@material-ui/icons/SurroundSoundOutlined'));
export const TableChartOutlined = loadableIcon(() => import('@material-ui/icons/TableChartOutlined'));
export const TabletAndroidOutlined = loadableIcon(() => import('@material-ui/icons/TabletAndroidOutlined'));
export const TabletMacOutlined = loadableIcon(() => import('@material-ui/icons/TabletMacOutlined'));
export const TabOutlined = loadableIcon(() => import('@material-ui/icons/TabOutlined'));
export const TagFacesOutlined = loadableIcon(() => import('@material-ui/icons/TagFacesOutlined'));
export const TerrainOutlined = loadableIcon(() => import('@material-ui/icons/TerrainOutlined'));
export const TextsmsOutlined = loadableIcon(() => import('@material-ui/icons/TextsmsOutlined'));
export const TheatersOutlined = loadableIcon(() => import('@material-ui/icons/TheatersOutlined'));
export const ThumbDownAltOutlined = loadableIcon(() => import('@material-ui/icons/ThumbDownAltOutlined'));
export const ThumbsUpDownOutlined = loadableIcon(() => import('@material-ui/icons/ThumbsUpDownOutlined'));
export const ThumbUpAltOutlined = loadableIcon(() => import('@material-ui/icons/ThumbUpAltOutlined'));
export const TimelapseOutlined = loadableIcon(() => import('@material-ui/icons/TimelapseOutlined'));
export const TimerOutlined = loadableIcon(() => import('@material-ui/icons/TimerOutlined'));
export const TimeToLeaveOutlined = loadableIcon(() => import('@material-ui/icons/TimeToLeaveOutlined'));
export const TodayOutlined = loadableIcon(() => import('@material-ui/icons/TodayOutlined'));
export const TonalityOutlined = loadableIcon(() => import('@material-ui/icons/TonalityOutlined'));
export const TouchAppOutlined = loadableIcon(() => import('@material-ui/icons/TouchAppOutlined'));
export const ToysOutlined = loadableIcon(() => import('@material-ui/icons/ToysOutlined'));
export const TrackChangesOutlined = loadableIcon(() => import('@material-ui/icons/TrackChangesOutlined'));
export const TrafficOutlined = loadableIcon(() => import('@material-ui/icons/TrafficOutlined'));
export const TrainOutlined = loadableIcon(() => import('@material-ui/icons/TrainOutlined'));
export const TramOutlined = loadableIcon(() => import('@material-ui/icons/TramOutlined'));
export const TransferWithinAStationOutlined = loadableIcon(() => import('@material-ui/icons/TransferWithinAStationOutlined'));
export const TranslateOutlined = loadableIcon(() => import('@material-ui/icons/TranslateOutlined'));
export const TurnedInNotOutlined = loadableIcon(() => import('@material-ui/icons/TurnedInNotOutlined'));
export const TurnedInOutlined = loadableIcon(() => import('@material-ui/icons/TurnedInOutlined'));
export const TvOutlined = loadableIcon(() => import('@material-ui/icons/TvOutlined'));
export const TwoWheelerOutlined = loadableIcon(() => import('@material-ui/icons/TwoWheelerOutlined'));
export const UnarchiveOutlined = loadableIcon(() => import('@material-ui/icons/UnarchiveOutlined'));
export const UsbOutlined = loadableIcon(() => import('@material-ui/icons/UsbOutlined'));
export const VerifiedUserOutlined = loadableIcon(() => import('@material-ui/icons/VerifiedUserOutlined'));
export const VideocamOutlined = loadableIcon(() => import('@material-ui/icons/VideocamOutlined'));
export const VideogameAssetOutlined = loadableIcon(() => import('@material-ui/icons/VideogameAssetOutlined'));
export const ViewQuiltOutlined = loadableIcon(() => import('@material-ui/icons/ViewQuiltOutlined'));
export const VisibilityOutlined = loadableIcon(() => import('@material-ui/icons/VisibilityOutlined'));
export const VoiceChatOutlined = loadableIcon(() => import('@material-ui/icons/VoiceChatOutlined'));
export const VpnKeyOutlined = loadableIcon(() => import('@material-ui/icons/VpnKeyOutlined'));
export const VpnLockOutlined = loadableIcon(() => import('@material-ui/icons/VpnLockOutlined'));
export const WarningOutlined = loadableIcon(() => import('@material-ui/icons/WarningOutlined'));
export const WatchLaterOutlined = loadableIcon(() => import('@material-ui/icons/WatchLaterOutlined'));
export const WatchOutlined = loadableIcon(() => import('@material-ui/icons/WatchOutlined'));
export const WavesOutlined = loadableIcon(() => import('@material-ui/icons/WavesOutlined'));
export const WbCloudyOutlined = loadableIcon(() => import('@material-ui/icons/WbCloudyOutlined'));
export const WbIncandescentOutlined = loadableIcon(() => import('@material-ui/icons/WbIncandescentOutlined'));
export const WbIridescentOutlined = loadableIcon(() => import('@material-ui/icons/WbIridescentOutlined'));
export const WbSunnyOutlined = loadableIcon(() => import('@material-ui/icons/WbSunnyOutlined'));
export const WcOutlined = loadableIcon(() => import('@material-ui/icons/WcOutlined'));
export const WebAssetOutlined = loadableIcon(() => import('@material-ui/icons/WebAssetOutlined'));
export const WebOutlined = loadableIcon(() => import('@material-ui/icons/WebOutlined'));
export const WeekendOutlined = loadableIcon(() => import('@material-ui/icons/WeekendOutlined'));
export const WhatshotOutlined = loadableIcon(() => import('@material-ui/icons/WhatshotOutlined'));
export const WhereToVoteOutlined = loadableIcon(() => import('@material-ui/icons/WhereToVoteOutlined'));
export const WifiOutlined = loadableIcon(() => import('@material-ui/icons/WifiOutlined'));
export const WorkOutlined = loadableIcon(() => import('@material-ui/icons/WorkOutlined'));
export const WorkOutlineOutlined = loadableIcon(() => import('@material-ui/icons/WorkOutlineOutlined'));
export const ZoomInOutlined = loadableIcon(() => import('@material-ui/icons/ZoomInOutlined'));
