export const COMMON_SETUP_APP_BEGIN = 'COMMON_SETUP_APP_BEGIN';
export const COMMON_SETUP_APP_SUCCESS = 'COMMON_SETUP_APP_SUCCESS';
export const COMMON_SETUP_APP_FAILURE = 'COMMON_SETUP_APP_FAILURE';
export const COMMON_SETUP_APP_DISMISS_ERROR = 'COMMON_SETUP_APP_DISMISS_ERROR';
