export const COMMON_SETUP_APP_BEGIN = 'COMMON_SETUP_APP_BEGIN';
export const COMMON_SETUP_APP_SUCCESS = 'COMMON_SETUP_APP_SUCCESS';
export const COMMON_SETUP_APP_FAILURE = 'COMMON_SETUP_APP_FAILURE';
export const COMMON_SETUP_APP_DISMISS_ERROR = 'COMMON_SETUP_APP_DISMISS_ERROR';
export const COMMON_EDIT_RUNNING_SESSION_BEGIN = 'COMMON_EDIT_RUNNING_SESSION_BEGIN';
export const COMMON_EDIT_RUNNING_SESSION_SUCCESS = 'COMMON_EDIT_RUNNING_SESSION_SUCCESS';
export const COMMON_EDIT_RUNNING_SESSION_FAILURE = 'COMMON_EDIT_RUNNING_SESSION_FAILURE';
export const COMMON_EDIT_RUNNING_SESSION_DISMISS_ERROR = 'COMMON_EDIT_RUNNING_SESSION_DISMISS_ERROR';
