export const STATS_GET_SESSIONS_BEGIN = 'STATS_GET_SESSIONS_BEGIN';
export const STATS_GET_SESSIONS_SUCCESS = 'STATS_GET_SESSIONS_SUCCESS';
export const STATS_GET_SESSIONS_FAILURE = 'STATS_GET_SESSIONS_FAILURE';
export const STATS_GET_SESSIONS_DISMISS_ERROR = 'STATS_GET_SESSIONS_DISMISS_ERROR';
