export const LOGIN_LOGIN_ACTION_BEGIN = 'LOGIN_LOGIN_ACTION_BEGIN';
export const LOGIN_LOGIN_ACTION_SUCCESS = 'LOGIN_LOGIN_ACTION_SUCCESS';
export const LOGIN_LOGIN_ACTION_FAILURE = 'LOGIN_LOGIN_ACTION_FAILURE';
export const LOGIN_LOGIN_ACTION_DISMISS_ERROR = 'LOGIN_LOGIN_ACTION_DISMISS_ERROR';
export const LOGIN_SIGN_UP_BEGIN = 'LOGIN_SIGN_UP_BEGIN';
export const LOGIN_SIGN_UP_SUCCESS = 'LOGIN_SIGN_UP_SUCCESS';
export const LOGIN_SIGN_UP_FAILURE = 'LOGIN_SIGN_UP_FAILURE';
export const LOGIN_SIGN_UP_DISMISS_ERROR = 'LOGIN_SIGN_UP_DISMISS_ERROR';
